config = {
  name: 'Telegram: Send a Message',
  description: 'Send a message to your Telegram channel',
  author: 'Victor',
  thumbnailUrl:
    'https://youai.imgix.net/images/9e603bae-0732-4f04-8136-2eeec1f0a9fe_1703054868463.png',
  blockStyle: {
    backgroundImageUrl:
      'https://youai.imgix.net/images/9e603bae-0732-4f04-8136-2eeec1f0a9fe_1703054868463.png',
    foregroundColor: '#ffffff',
    label: ' ',
  },
  configurationSections: [
    {
      title: 'Configuration',
      items: [
        {
          label: 'Telegram Bot API Key',
          variable: 'telegram_api_key',
          helpText: 'API Key generated by BotFather when you created your bot',
          type: 'secret',
        },
        {
          label: 'Telegram Channel',
          variable: 'telegram_channel',
          helpText: 'The handle of your channel (e.g. @my_channel_name). The channel must be public',
          type: 'text',
        },
        {
          label: 'Message',
          variable: 'telegram_message',
          helpText: 'Message can be a string or a {{variable}}.',
          type: 'text',
        },
      ],
    },
  ],
}
